package com.smartbudget.app.data.local.entity;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.io.Serializable;
import java.util.Objects;

/**
 * Entity class representing a financial category in the SmartBudget application.
 * 
 * Categories are used to classify expenses and income transactions, enabling:
 * - Organized expense tracking by type (food, transport, entertainment, etc.)
 * - Income source management (salary, gifts, investments, etc.)
 * - Budget allocation per category
 * - Statistical analysis and reporting by category
 * 
 * The application comes with pre-defined default categories (isCustom = false)
 * and allows users to create their own custom categories (isCustom = true).
 * 
 * Database Table: "categories"
 * 
 * Fields:
 * - id: Auto-generated primary key
 * - name: Display name of the category (e.g., "Ăn uống", "Di chuyển")
 * - icon: Emoji or icon code representing the category visually
 * - color: Hex color code for visual distinction in charts/UI
 * - type: 0 = Expense category, 1 = Income category
 * - isCustom: true if user-created, false if system default
 * 
 * Relationships:
 * - Referenced by ExpenseEntity (Many-to-One)
 * - Referenced by BudgetEntity (Many-to-One)
 * 
 * @author SmartBudget Development Team
 * @version 1.0
 * @since 2025-01
 * @see ExpenseEntity
 * @see BudgetEntity
 */
@Entity(tableName = "categories")
public class CategoryEntity implements Serializable {

    /** Serial version UID for serialization compatibility */
    private static final long serialVersionUID = 1L;

    /** Constant representing expense category type */
    public static final int TYPE_EXPENSE = 0;
    
    /** Constant representing income category type */
    public static final int TYPE_INCOME = 1;

    // ==================== Fields ====================

    /**
     * Unique identifier for the category.
     * Auto-generated by Room database.
     */
    @PrimaryKey(autoGenerate = true)
    private long id;

    /**
     * Display name of the category.
     * Examples: "Ăn uống", "Di chuyển", "Lương"
     * Required field, should not be null or empty.
     */
    private String name;

    /**
     * Visual icon for the category.
     * Typically an emoji character (e.g., "🍔", "🚗", "💰")
     * Used in lists, charts, and category selection UI.
     */
    private String icon;

    /**
     * Hex color code for the category.
     * Format: "#RRGGBB" (e.g., "#FF6B6B", "#4ECDC4")
     * Used for progress bars, pie charts, and visual distinction.
     */
    private String color;

    /**
     * Type of the category.
     * - 0 (TYPE_EXPENSE): Expense category (money going out)
     * - 1 (TYPE_INCOME): Income category (money coming in)
     */
    private int type;

    /**
     * Flag indicating if this is a user-created category.
     * - true: User-created custom category (can be deleted)
     * - false: System default category (cannot be deleted)
     */
    private boolean isCustom;

    // ==================== Constructors ====================

    /**
     * Default no-argument constructor.
     * Required by Room for entity instantiation.
     */
    public CategoryEntity() {
    }

    /**
     * Full constructor for creating a category with all properties.
     * 
     * @param name Display name of the category
     * @param icon Emoji or icon code
     * @param color Hex color code (e.g., "#FF6B6B")
     * @param type Category type (TYPE_EXPENSE or TYPE_INCOME)
     * @param isCustom Whether this is a user-created category
     */
    /**
     * Full constructor for creating a category with all properties.
     * 
     * @param name Display name of the category
     * @param icon Emoji or icon code
     * @param color Hex color code (e.g., "#FF6B6B")
     * @param type Category type (TYPE_EXPENSE or TYPE_INCOME)
     * @param isCustom Whether this is a user-created category
     */
    @androidx.room.Ignore
    public CategoryEntity(String name, String icon, String color, int type, boolean isCustom) {
        this.name = name;
        this.icon = icon;
        this.color = color;
        this.type = type;
        this.isCustom = isCustom;
    }

    /**
     * Convenience constructor for system default categories.
     * Sets isCustom to false automatically.
     * 
     * @param name Display name of the category
     * @param icon Emoji or icon code
     * @param color Hex color code
     * @param type Category type
     */
    /**
     * Convenience constructor for system default categories.
     * Sets isCustom to false automatically.
     * 
     * @param name Display name of the category
     * @param icon Emoji or icon code
     * @param color Hex color code
     * @param type Category type
     */
    @androidx.room.Ignore
    public CategoryEntity(String name, String icon, String color, int type) {
        this(name, icon, color, type, false);
    }

    // ==================== Getters and Setters ====================

    /**
     * Gets the unique identifier of this category.
     * 
     * @return Category ID
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of this category.
     * Note: ID is auto-generated, this should only be used by Room.
     * 
     * @param id Category ID
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Gets the display name of this category.
     * 
     * @return Category name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the display name of this category.
     * 
     * @param name Category name (should not be null or empty)
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the visual icon/emoji for this category.
     * 
     * @return Icon string (emoji)
     */
    public String getIcon() {
        return icon;
    }

    /**
     * Sets the visual icon for this category.
     * 
     * @param icon Icon string (emoji or icon code)
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * Gets the hex color code for this category.
     * 
     * @return Color code in format "#RRGGBB"
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the color code for this category.
     * 
     * @param color Hex color code (e.g., "#FF6B6B")
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * Gets the type of this category.
     * 
     * @return TYPE_EXPENSE (0) or TYPE_INCOME (1)
     */
    public int getType() {
        return type;
    }

    /**
     * Sets the type of this category.
     * 
     * @param type TYPE_EXPENSE (0) or TYPE_INCOME (1)
     */
    public void setType(int type) {
        this.type = type;
    }

    /**
     * Checks if this is a user-created custom category.
     * 
     * @return true if user-created, false if system default
     */
    public boolean isCustom() {
        return isCustom;
    }

    /**
     * Sets whether this is a user-created custom category.
     * 
     * @param custom true for user-created, false for system default
     */
    public void setCustom(boolean custom) {
        isCustom = custom;
    }

    // ==================== Convenience Methods ====================

    /**
     * Checks if this category is for expenses (money going out).
     * 
     * @return true if this is an expense category
     */
    public boolean isExpense() {
        return type == TYPE_EXPENSE;
    }

    /**
     * Checks if this category is for income (money coming in).
     * 
     * @return true if this is an income category
     */
    public boolean isIncome() {
        return type == TYPE_INCOME;
    }

    /**
     * Gets a formatted display string combining icon and name.
     * Example: "🍔 Ăn uống"
     * 
     * @return Formatted display string
     */
    public String getDisplayName() {
        if (icon != null && !icon.isEmpty()) {
            return icon + " " + name;
        }
        return name;
    }

    /**
     * Gets the color as an Android Color integer.
     * Returns a default color if parsing fails.
     * 
     * @return Color as integer value
     */
    public int getColorInt() {
        try {
            return android.graphics.Color.parseColor(color);
        } catch (Exception e) {
            // Return default gray if parsing fails
            return android.graphics.Color.parseColor("#95979A");
        }
    }

    /**
     * Checks if this category can be deleted.
     * Only custom categories can be deleted.
     * 
     * @return true if category can be deleted
     */
    public boolean isDeletable() {
        return isCustom;
    }

    /**
     * Gets a human-readable type description.
     * 
     * @return "Chi tiêu" for expense, "Thu nhập" for income
     */
    public String getTypeDescription() {
        return isExpense() ? "Chi tiêu" : "Thu nhập";
    }

    // ==================== Object Methods ====================

    /**
     * Compares this category with another object for equality.
     * Two categories are equal if they have the same ID.
     * 
     * @param o Object to compare with
     * @return true if equal, false otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        CategoryEntity that = (CategoryEntity) o;
        return id == that.id;
    }

    /**
     * Generates a hash code for this category based on ID.
     * 
     * @return Hash code
     */
    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    /**
     * Returns a string representation of this category.
     * Useful for debugging purposes.
     * 
     * @return String representation including all fields
     */
    @Override
    public String toString() {
        return "CategoryEntity{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", icon='" + icon + '\'' +
                ", color='" + color + '\'' +
                ", type=" + type +
                ", isCustom=" + isCustom +
                '}';
    }

    // ==================== Builder Pattern ====================

    /**
     * Creates a new Builder for constructing CategoryEntity instances.
     * 
     * @return New Builder instance
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builder class for creating CategoryEntity instances.
     * Provides a fluent API for setting properties.
     */
    public static class Builder {
        private String name;
        private String icon;
        private String color;
        private int type = TYPE_EXPENSE;
        private boolean isCustom = false;

        /**
         * Sets the category name.
         * 
         * @param name Category name
         * @return This builder for chaining
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Sets the category icon.
         * 
         * @param icon Icon emoji
         * @return This builder for chaining
         */
        public Builder icon(String icon) {
            this.icon = icon;
            return this;
        }

        /**
         * Sets the category color.
         * 
         * @param color Hex color code
         * @return This builder for chaining
         */
        public Builder color(String color) {
            this.color = color;
            return this;
        }

        /**
         * Sets the category type.
         * 
         * @param type TYPE_EXPENSE or TYPE_INCOME
         * @return This builder for chaining
         */
        public Builder type(int type) {
            this.type = type;
            return this;
        }

        /**
         * Sets whether this is a custom category.
         * 
         * @param isCustom true for custom, false for default
         * @return This builder for chaining
         */
        public Builder custom(boolean isCustom) {
            this.isCustom = isCustom;
            return this;
        }

        /**
         * Marks this as an expense category.
         * 
         * @return This builder for chaining
         */
        public Builder asExpense() {
            this.type = TYPE_EXPENSE;
            return this;
        }

        /**
         * Marks this as an income category.
         * 
         * @return This builder for chaining
         */
        public Builder asIncome() {
            this.type = TYPE_INCOME;
            return this;
        }

        /**
         * Builds and returns the CategoryEntity instance.
         * 
         * @return New CategoryEntity with the configured properties
         */
        public CategoryEntity build() {
            return new CategoryEntity(name, icon, color, type, isCustom);
        }
    }
}
